//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCP_File_Transfer.LanguageManager.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_en() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCP_File_Transfer.LanguageManager.Languages.Lang_en", typeof(Lang_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   File Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wait for File...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnReceiveFile {
            get {
                return ResourceManager.GetString("btnReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSelectSaveLocation {
            get {
                return ResourceManager.GetString("btnSelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSendFile {
            get {
                return ResourceManager.GetString("btnSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Sending과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel the Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelTransfer {
            get {
                return ResourceManager.GetString("CancelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel Waiting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelWaiting {
            get {
                return ResourceManager.GetString("CancelWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Request Has Came과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileRequestHasCame {
            get {
                return ResourceManager.GetString("FileRequestHasCame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File request just came up, waiting user response...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileRequestJustComeUpWaitingUserResponse {
            get {
                return ResourceManager.GetString("FileRequestJustComeUpWaitingUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Being Sending...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileSending {
            get {
                return ResourceManager.GetString("FileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Waiting Was Cancelled by User과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileWaitingWasCancelled {
            get {
                return ResourceManager.GetString("FileWaitingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About File Transfer App과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupBoxAboutApp {
            get {
                return ResourceManager.GetString("GroupBoxAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About Developer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupBoxAboutDeveloper {
            get {
                return ResourceManager.GetString("GroupBoxAboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a valid file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFilenameMessage {
            get {
                return ResourceManager.GetString("InvalidFilenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFilenameMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFilenameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please check the data you have entered on the form.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFormInputMessage {
            get {
                return ResourceManager.GetString("InvalidFormInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Data Entry과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFormInputMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFormInputMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a valid IP address.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidIpAddressMessage {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid IP Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidIpAddressMessageTitle {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter a valid port number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPortNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Port Number과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPortNumberMessageTitle {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please select a valid save location.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSaveLocationMessage {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid Save Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSaveLocationMessageTitle {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © {0} {1} - All Right Reserved과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAllRightReserved {
            get {
                return ResourceManager.GetString("labelAllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Github Repository과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAppGithubRepository {
            get {
                return ResourceManager.GetString("labelAppGithubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - Version {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAppNameAndVersion {
            get {
                return ResourceManager.GetString("labelAppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Github Profile: @FiratEski과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperGithubProfile {
            get {
                return ResourceManager.GetString("labelDeveloperGithubProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firat Eski / @firateski / firateski@outlook.com과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperName {
            get {
                return ResourceManager.GetString("labelDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Developer Website: FiratEski.com과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperWebSite {
            get {
                return ResourceManager.GetString("labelDeveloperWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelFileLocation {
            get {
                return ResourceManager.GetString("labelFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelReceiverIPAdress {
            get {
                return ResourceManager.GetString("labelReceiverIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelReceiverPort {
            get {
                return ResourceManager.GetString("labelReceiverPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save Location과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSaveLocation {
            get {
                return ResourceManager.GetString("labelSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Address과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSenderIPAdress {
            get {
                return ResourceManager.GetString("labelSenderIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSenderPort {
            get {
                return ResourceManager.GetString("labelSenderPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to receive the file &quot;{0}&quot; which is {1} in size?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverAskForReceiveFile {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do You Want to Receive The File?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverAskForReceiveFileTitle {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file receiving cancelled by user.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCancelledByUser {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive Cancelled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCancelledByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file received successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCompleted {
            get {
                return ResourceManager.GetString("ReceiverCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCompletedTitle {
            get {
                return ResourceManager.GetString("ReceiverCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be received because the data could not be read from the stream.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCouldntReadStream {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File Read Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCouldntReadStreamTitle {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An unknown error has occurred while receiving the file:
        ///
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverException {
            get {
                return ResourceManager.GetString("ReceiverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknown Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be received due to that either the remote user cancelled or the connection is lost.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFailed {
            get {
                return ResourceManager.GetString("ReceiverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFailedTitle {
            get {
                return ResourceManager.GetString("ReceiverFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File receiving was cancelled at your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFileRejectedByUser {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive Cancelled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFileRejectedByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be received due to I/O error which is can cause the invalid save location or other write exceptions.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException {
            get {
                return ResourceManager.GetString("ReceiverIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be sent due to either the remote user cancelled or the connection lost.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException10054 {
            get {
                return ResourceManager.GetString("ReceiverIOException10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The File Could Not Send과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException10054Title {
            get {
                return ResourceManager.GetString("ReceiverIOException10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   second과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be sent due to the error that occurred in the sender argument. Please try again after resetting your settings and restarting the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentException {
            get {
                return ResourceManager.GetString("SenderArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument Exception과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be sent because of the invalid argument of sender. Please try again after resetting your settings and restarting the application.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentNullException {
            get {
                return ResourceManager.GetString("SenderArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argument Invalid Exception과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentNullExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentNullExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file sending was cancelled at your request.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCancelledByUser {
            get {
                return ResourceManager.GetString("SenderCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Operation Cancelled과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCancelledByUserTitle {
            get {
                return ResourceManager.GetString("SenderCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file sent successfully.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCompleted {
            get {
                return ResourceManager.GetString("SenderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Operation Completed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCompletedTitle {
            get {
                return ResourceManager.GetString("SenderCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not connect to IP address due to the one of the following reasons:
        ///
        ///1- The remote user did not switch the program to the file wait mode.
        ///2- The IP address or port number wasn&apos;t match with the remote user.
        ///3- The remote user did not configure the port forwarding.
        ///4- You or remote user have no internet connection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderConnectError {
            get {
                return ResourceManager.GetString("SenderConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderConnectErrorTitle {
            get {
                return ResourceManager.GetString("SenderConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file could not be sent due to cannot write data to the stream.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCouldntWriteToStream {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stream Write Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCouldntWriteToStreamTitle {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The directory you specified could not be found. Please make sure you select a valid save path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderDirectoryNotFoundException {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory Not Found Exception과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderDirectoryNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error occurred while sending file:
        ///
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderException {
            get {
                return ResourceManager.GetString("SenderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected Error Occurred과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderExceptionTitle {
            get {
                return ResourceManager.GetString("SenderExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error occurred while sending file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderFailed {
            get {
                return ResourceManager.GetString("SenderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Send Failed과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderFailedTitle {
            get {
                return ResourceManager.GetString("SenderFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be sent due to I/O error which is can cause the invalid file location or other read exceptions.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOException {
            get {
                return ResourceManager.GetString("SenderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be sent due to that either the remote user cancelled or the connection is lost.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionError10054 {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connection Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionError10054Title {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   I/O Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionTitle {
            get {
                return ResourceManager.GetString("SenderIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file sending couldn&apos;t be started due to selected path is too long. Please select a shorter path and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderPathTooLongException {
            get {
                return ResourceManager.GetString("SenderPathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path Too Long Exception과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderPathTooLongExceptionTitle {
            get {
                return ResourceManager.GetString("SenderPathTooLongExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file couldn&apos;t be sent due to the unauthorized exception which can prevent the file to being read. Please try again after restarting the application with administrator privileges.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unauthorized Exception과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderUnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageAbout {
            get {
                return ResourceManager.GetString("TabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Receive File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageReceiver {
            get {
                return ResourceManager.GetString("TabPageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageSender {
            get {
                return ResourceManager.GetString("TabPageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to select file...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtFileLocation {
            get {
                return ResourceManager.GetString("txtFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Click to select save location...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtSaveLocation {
            get {
                return ResourceManager.GetString("txtSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Waiting for File...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaitingForFile {
            get {
                return ResourceManager.GetString("WaitingForFile", resourceCulture);
            }
        }
    }
}
