//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCP_File_Transfer.LanguageManager.Languages {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_tr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_tr() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TCP_File_Transfer.LanguageManager.Languages.Lang_tr", typeof(Lang_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Dosya Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Bekle...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnReceiveFile {
            get {
                return ResourceManager.GetString("btnReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Seç과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSelectFile {
            get {
                return ResourceManager.GetString("btnSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Yeri Seç과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSelectSaveLocation {
            get {
                return ResourceManager.GetString("btnSelectSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosyayı Gönder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string btnSendFile {
            get {
                return ResourceManager.GetString("btnSendFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Göndermeyi İptal Et과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelSending {
            get {
                return ResourceManager.GetString("CancelSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transferi İptal Et과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelTransfer {
            get {
                return ResourceManager.GetString("CancelTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beklemeyi İptal Et과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CancelWaiting {
            get {
                return ResourceManager.GetString("CancelWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya İsteği Geldi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileRequestHasCame {
            get {
                return ResourceManager.GetString("FileRequestHasCame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya isteği geldi, kullanıcıdan yanıt bekleniyor...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileRequestJustComeUpWaitingUserResponse {
            get {
                return ResourceManager.GetString("FileRequestJustComeUpWaitingUserResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Gönderiliyor...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileSending {
            get {
                return ResourceManager.GetString("FileSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Bekleme İptal Edildi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileWaitingWasCancelled {
            get {
                return ResourceManager.GetString("FileWaitingWasCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Transfer Uygulaması Hakkında과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupBoxAboutApp {
            get {
                return ResourceManager.GetString("GroupBoxAboutApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geliştirici Hakkında과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GroupBoxAboutDeveloper {
            get {
                return ResourceManager.GetString("GroupBoxAboutDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geçerli bir dosya seçiniz.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFilenameMessage {
            get {
                return ResourceManager.GetString("InvalidFilenameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Dosya과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFilenameMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFilenameMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen girdiğiniz bilgileri kontrol ediniz.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFormInputMessage {
            get {
                return ResourceManager.GetString("InvalidFormInputMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Veri Girişi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidFormInputMessageTitle {
            get {
                return ResourceManager.GetString("InvalidFormInputMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geçerli bir IP adresi giriniz.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidIpAddressMessage {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz IP Adresi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidIpAddressMessageTitle {
            get {
                return ResourceManager.GetString("InvalidIpAddressMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geçerli bir port numarası giriniz.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPortNumberMessage {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Port Numarası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidPortNumberMessageTitle {
            get {
                return ResourceManager.GetString("InvalidPortNumberMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lütfen geçerli bir kayıt dizini seçiniz.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSaveLocationMessage {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Kayıt Dizini과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSaveLocationMessageTitle {
            get {
                return ResourceManager.GetString("InvalidSaveLocationMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   © {0} {1} - Tüm Hakları Saklıdır과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAllRightReserved {
            get {
                return ResourceManager.GetString("labelAllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} Github Repository과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAppGithubRepository {
            get {
                return ResourceManager.GetString("labelAppGithubRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - Versiyon {1}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelAppNameAndVersion {
            get {
                return ResourceManager.GetString("labelAppNameAndVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geliştirici Github Profili: @FiratEski과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperGithubProfile {
            get {
                return ResourceManager.GetString("labelDeveloperGithubProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fırat Eşki / @firateski / firateski@outlook.com과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperName {
            get {
                return ResourceManager.GetString("labelDeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geliştirici Web Sitesi: FiratEski.com과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelDeveloperWebSite {
            get {
                return ResourceManager.GetString("labelDeveloperWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelFileLocation {
            get {
                return ResourceManager.GetString("labelFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Adresi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelReceiverIPAdress {
            get {
                return ResourceManager.GetString("labelReceiverIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelReceiverPort {
            get {
                return ResourceManager.GetString("labelReceiverPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Yeri과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSaveLocation {
            get {
                return ResourceManager.GetString("labelSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IP Adresi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSenderIPAdress {
            get {
                return ResourceManager.GetString("labelSenderIPAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string labelSenderPort {
            get {
                return ResourceManager.GetString("labelSenderPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Transfer과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MainView {
            get {
                return ResourceManager.GetString("MainView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; ismindeki {1} boyutundaki dosyayı almak istiyor musunuz?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverAskForReceiveFile {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya alınsın mı?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverAskForReceiveFileTitle {
            get {
                return ResourceManager.GetString("ReceiverAskForReceiveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya alımı kullanıcı tarafından iptal edildi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCancelledByUser {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem İptal Edildi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCancelledByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya başarıyla alındı.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCompleted {
            get {
                return ResourceManager.GetString("ReceiverCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Tamamlandı과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCompletedTitle {
            get {
                return ResourceManager.GetString("ReceiverCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akıştan veri okunamadığı için dosya alınamadı.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCouldntReadStream {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veri Okuma Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverCouldntReadStreamTitle {
            get {
                return ResourceManager.GetString("ReceiverCouldntReadStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya alınırken bilinmeyen bir sorun oluştu:
        ///
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverException {
            get {
                return ResourceManager.GetString("ReceiverException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beklenmeyen Bir Hata Oluştu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya alınamadı.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFailed {
            get {
                return ResourceManager.GetString("ReceiverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Tamamlanamadı과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFailedTitle {
            get {
                return ResourceManager.GetString("ReceiverFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya alımını kabul etmediğiniz için dosya alımı iptal edildi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFileRejectedByUser {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem İptal Edildi!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverFileRejectedByUserTitle {
            get {
                return ResourceManager.GetString("ReceiverFileRejectedByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt dizininden veya başka bir nedenden dolayı G/Ç hatası meydana geldiği için dosya alınamadı.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException {
            get {
                return ResourceManager.GetString("ReceiverIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya gönderilemedi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException10054 {
            get {
                return ResourceManager.GetString("ReceiverIOException10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Gönderilemedi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOException10054Title {
            get {
                return ResourceManager.GetString("ReceiverIOException10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G/Ç Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReceiverIOExceptionTitle {
            get {
                return ResourceManager.GetString("ReceiverIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   saniye과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderme parametrelerinde meydana gelen sorundan dolayı gönderme işlemi yapılamıyor. Lütfen Ayarlarınızı gözden geçirip programı yeniden başlattıktan sonra işleminizi tekrarlayın.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentException {
            get {
                return ResourceManager.GetString("SenderArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Argüman Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gönderme parametrelerinde geçersiz parametreden dolayı gönderme işlemi yapılamıyor. Lütfen Ayarlarınızı gözden geçirip programı yeniden başlattıktan sonra işleminizi tekrarlayın.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentNullException {
            get {
                return ResourceManager.GetString("SenderArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Argüman Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderArgumentNullExceptionTitle {
            get {
                return ResourceManager.GetString("SenderArgumentNullExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya gönderme kullanıcı tarafından iptal edildi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCancelledByUser {
            get {
                return ResourceManager.GetString("SenderCancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem İptal Edildi과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCancelledByUserTitle {
            get {
                return ResourceManager.GetString("SenderCancelledByUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya başarıyla gönderildi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCompleted {
            get {
                return ResourceManager.GetString("SenderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Tamamlandı과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCompletedTitle {
            get {
                return ResourceManager.GetString("SenderCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İstenilen IP adresiyle bağlantı sağlanamadı. Olası nedenler:
        ///
        ///1- Karşıdaki kullanıcı dosya bekleme moduna geçmemiş olabilir.
        ///2- IP adresi veya port numarası eşleşmemiş olabilir.
        ///3- Karşıdaki kullanıcı gerekli port yapılandırmasını yapmamış olabilir.
        ///4- İnternet bağlantınız veya karşı tarafın internet bağlantısı olmayabilir.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderConnectError {
            get {
                return ResourceManager.GetString("SenderConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderConnectErrorTitle {
            get {
                return ResourceManager.GetString("SenderConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Akışa veri yazılamadığı için dosya gönderilemedi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCouldntWriteToStream {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veri Yazma Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderCouldntWriteToStreamTitle {
            get {
                return ResourceManager.GetString("SenderCouldntWriteToStreamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Belirtilen dizin bulunamadı. Lütfen geçerli bir dosya seçtiğinize emin olun.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderDirectoryNotFoundException {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçersiz Dizin Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderDirectoryNotFoundExceptionTitle {
            get {
                return ResourceManager.GetString("SenderDirectoryNotFoundExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya gönderilirken bilinmeyen bir hata oluştu:
        ///
        ///{0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderException {
            get {
                return ResourceManager.GetString("SenderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beklenmeyen Bir Hata Oluştu과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderExceptionTitle {
            get {
                return ResourceManager.GetString("SenderExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya gönderilirken hata oluştu.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderFailed {
            get {
                return ResourceManager.GetString("SenderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Gönderme Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderFailedTitle {
            get {
                return ResourceManager.GetString("SenderFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seçtiğiniz dosya bulunamadığından veya dosyayı okuma izni olmadığından dolayı G/Ç hatası meydana geldi ve dosya gönderilemedi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOException {
            get {
                return ResourceManager.GetString("SenderIOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Karşı taraf bağlantıyı iptal ettiği için veya bağlantı koptuğu için dosya gönderilemedi.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionError10054 {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bağlantı Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionError10054Title {
            get {
                return ResourceManager.GetString("SenderIOExceptionError10054Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   G/Ç Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderIOExceptionTitle {
            get {
                return ResourceManager.GetString("SenderIOExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya yolu çok uzun olduğu için dosya gönderme işlemine başlanamadı. Lütfen daha kısa bir yol ile yeniden deneyin.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderPathTooLongException {
            get {
                return ResourceManager.GetString("SenderPathTooLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Yolu Hatası과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderPathTooLongExceptionTitle {
            get {
                return ResourceManager.GetString("SenderPathTooLongExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gerekli yetkiler bulunmadığı için dosya gönderilemedi. Programı yönetici olarak çalıştırıp tekrar göndermeyi deneyin.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderUnauthorizedAccessException {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Güvenlikten Kaynaklı Hata과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SenderUnauthorizedAccessExceptionTitle {
            get {
                return ResourceManager.GetString("SenderUnauthorizedAccessExceptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hakkında과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageAbout {
            get {
                return ResourceManager.GetString("TabPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Al과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageReceiver {
            get {
                return ResourceManager.GetString("TabPageReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Gönder과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TabPageSender {
            get {
                return ResourceManager.GetString("TabPageSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya seçmek için tıklayın...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtFileLocation {
            get {
                return ResourceManager.GetString("txtFileLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt yeri seçmek için tıklayın...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string txtSaveLocation {
            get {
                return ResourceManager.GetString("txtSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dosya Bekleniyor...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WaitingForFile {
            get {
                return ResourceManager.GetString("WaitingForFile", resourceCulture);
            }
        }
    }
}
